markdown        : redcarpet
tagLine         : Облачный файловый менеджер с консолью и редактором.
viewOn          : Посмотреть на
download        : Скачать
maintainedBy    : Проект поддерживает
yandex          : 536737db9426479f
